### ISSUE TITLE
Bổ sung thêm API

### ISSUE THREAD

**Issue by Fuon1412** [bachhungcb/THCSDL#47]
1. Viết query truy vấn producer và số lượng anime producer đó đã sản xuất, sắp xếp theo thứ tự điểm trung bình các phim từ cao đến thấp rồi xuất thành API .
2. Tương tự với truy vấn 1 producer có producer id cụ thể, lấy các thông tin về producer, kiểm tra xem đã có search anime by producer id chưa, nếu chưa bổ sung thêm.

**Comment by bachhungcb** [comment]
ok ni
